import type {
  DeterministicSceneChecksPort, DeterministicCheckResult,
} from '@application/pipeline/stage/JudgeStoryboardStage.js';
import type { Scene } from '@domain/script/Scene.js';
import { HtmlSanitizer } from '../render/HtmlSanitizer.js';

/**
 * Stage A: deterministic, no model, effectively free.
 *
 * Runs the checks that need no rendering — schema validity, anchor resolution
 * and duration fit. Geometry is *also* checked deterministically now, but from
 * the laid-out page rather than from markup: see `render/page/measure.ts`, which
 * the previewer runs against the same settled frame it screenshots.
 *
 * Two checks that used to live here are gone because the thing they guarded no
 * longer exists. Component cardinality went with the fixed vocabulary. A8 — "is
 * this board a picture rather than a paragraph" — went with model-authored
 * markup: every board is now produced by `renderDiagram` from a validated
 * `SceneDiagram`, so a text-only board is not something the system can express.
 * A check that cannot fail is worse than no check, because it reads as coverage.
 */
export class DeterministicSceneChecks implements DeterministicSceneChecksPort {
  constructor(private readonly sanitizer: HtmlSanitizer = new HtmlSanitizer()) {}

  public async check(input: { scenes: readonly Scene[] }): Promise<readonly DeterministicCheckResult[]> {
    return input.scenes.map((scene) => ({
      sceneIndex: scene.index,
      failures: [
        ...this.checkSchema(scene),
        ...this.checkAnchors(scene),
        ...this.checkDurationFit(scene),
      ],
      screenshotPaths: [],
    }));
  }

  /**
   * A1: the markup is well-formed and renderable.
   *
   * This used to filter out violations the sanitizer repairs on its own, because
   * a model-authored scene whose only sin was a `style=` attribute would
   * otherwise burn three retries being told to fix something already fixed.
   * That carve-out is gone: the markup is generated by `renderDiagram` now, so
   * any violation here is a bug in this service rather than a model's mistake,
   * and it should be loud. `test/contract/vocabulary.test.ts` asserts every
   * shape passes the sanitizer untouched, so this should never fire in practice.
   */
  private checkSchema(scene: Scene): string[] {
    if (!scene.html) return ['A1: scene has no storyboard HTML'];

    const { violations } = this.sanitizer.sanitize(scene.html);
    const failures = violations.map((v) => `A1: ${v}`);

    const titles = scene.html.match(/class\s*=\s*"[^"]*\bsc-title\b/g)?.length ?? 0;
    if (titles !== 1) failures.push(`A1: expected exactly one sc-title, found ${titles}`);

    return failures;
  }

  /**
   * A3: more than one unmatched `data-on` per scene is a failure.
   *
   * One is tolerated because the documented fallback (inherit the previous
   * element's time) degrades gracefully; two or more means the model is not
   * anchoring against the narration it was given, and the sync will visibly drift.
   */
  private checkAnchors(scene: Scene): string[] {
    if (!scene.html) return [];

    const anchors = [...scene.html.matchAll(/data-on\s*=\s*"([^"]*)"/g)]
      .map((m) => m[1] ?? '')
      .filter(Boolean);

    const haystack = scene.spokenText.toLowerCase().replace(/\s+/g, ' ');
    const unmatched = anchors.filter(
      (anchor) => !haystack.includes(anchor.toLowerCase().replace(/\s+/g, ' ')),
    );

    return unmatched.length > 1
      ? [`A3: ${unmatched.length} data-on phrases do not appear in the narration (${unmatched.slice(0, 3).join(', ')})`]
      : [];
  }

  /** A7: scene narration duration against its allotted window. */
  private checkDurationFit(scene: Scene): string[] {
    const measured = scene.measuredDuration;
    if (!measured) return []; // pre-synthesis: the estimate is all there is

    const estimated = scene.estimatedDuration;
    const drift = Math.abs(measured.ms - estimated.ms) / Math.max(1, estimated.ms);

    return drift > 0.5
      ? [`A7: measured audio (${measured.seconds.toFixed(1)}s) differs from the estimate (${estimated.seconds.toFixed(1)}s) by ${Math.round(drift * 100)}%`]
      : [];
  }
}
