import { describe, it, expect } from 'vitest';
import { DeterministicSceneChecks } from '@infrastructure/judge/DeterministicSceneChecks.js';
import { Scene } from '@domain/script/Scene.js';
import { SceneTimeline } from '@domain/script/SceneTimeline.js';
import { Duration } from '@domain/shared/Duration.js';
import { Citation } from '@domain/content/Citation.js';
import { SourceRef } from '@domain/content/SourceRef.js';
import { DIAGRAM_SHAPES, SHAPE_LIMITS } from '@domain/script/DiagramShape.js';
import { diagramFor } from '../helpers/diagrams.js';
import { renderDiagram } from '@infrastructure/render/diagram/renderDiagram.js';

const checks = new DeterministicSceneChecks();

const sceneWith = (html: string) => Scene.of({
  index: 0,
  spokenText: 'glycolysis splits glucose into pyruvate',
  citations: [Citation.of('c0', [SourceRef.page('doc', 1)])],
  visualIntent: 'parts',
  estimatedDuration: Duration.fromMs(6000),
}).withStoryboard(html, SceneTimeline.unresolved([]));

const failuresFor = async (html: string): Promise<readonly string[]> =>
  (await checks.check({ scenes: [sceneWith(html)] }))[0]!.failures;

/**
 * Stage A gates the retry budget, so what it fails on decides what costs money.
 *
 * A scene rejected here is regenerated up to the budget and then fails the whole
 * job — so failing on something the sanitizer silently repairs on the way to the
 * renderer spends three model calls to reject markup that was already fine.
 */
describe('Stage A schema checks', () => {
  it('passes a well-formed scene that actually draws something', async () => {
    expect(await failuresFor(
      '<section class="sc-scene"><style>.sc-title{color:var(--ink-primary)}</style>' +
      '<h2 class="sc-title">Glycolysis</h2>' +
      '<div class="sc-flow"><div class="sc-node">Glucose</div><div class="sc-node">Pyruvate</div></div>' +
      '</section>',
    )).toEqual([]);
  });

  /**
   * This assertion is the reverse of what it used to be, and deliberately so.
   * While a model authored the markup, an inline style was its mistake and the
   * sanitizer quietly fixed it — failing the gate meant burning three retries
   * telling it to fix something already fixed. The markup is generated by
   * `renderDiagram` now, so a `style=` attribute reaching here is *our* bug, and
   * it must be loud rather than repaired in silence.
   */
  it('fails a scene carrying an inline style, which the renderer never emits', async () => {
    const failures = await failuresFor(
      '<section class="sc-scene"><h2 class="sc-title" style="color:#f00">Glycolysis</h2>' +
      '<svg class="sc-link"><path class="sc-arrow" d="M0 0 H10"/></svg></section>',
    );
    expect(failures.join()).toMatch(/inline style/);
  });

  it('still fails a scene with no single title for the renderer to lay out around', async () => {
    expect(await failuresFor('<section class="sc-scene"><p class="sc-body">No title.</p></section>'))
      .toContainEqual(expect.stringContaining('sc-title'));
  });

  it('still fails a scene that references something external', async () => {
    const failures = await failuresFor(
      '<section class="sc-scene"><h2 class="sc-title">T</h2>' +
      '<img class="sc-pic" src="https://example.com/x.png"></section>',
    );
    expect(failures.length).toBeGreaterThan(0);
  });

  it('fails a scene with no markup at all', async () => {
    expect(await failuresFor('')).toContainEqual(expect.stringContaining('no storyboard HTML'));
  });
});

/**
 * A8 — "is this board a picture rather than a paragraph" — was deleted with
 * model-authored markup, and this records why rather than leaving a gap.
 *
 * It existed because every prompt revision that merely *asked* for diagrams
 * produced them only some of the time, so a board of text had to be refused.
 * Boards are now built by `renderDiagram` from a validated `SceneDiagram`, whose
 * vocabulary contains no way to describe a list — the property A8 enforced is
 * now the only thing the format can express.
 *
 * A check that cannot fail is worse than no check, because it reads as coverage.
 * The real guarantee is asserted in `test/unit/scene-diagram.test.ts` and
 * `test/integration/diagram-layout.test.ts`.
 */
describe('a board that is not a drawing is unrepresentable rather than rejected', () => {
  it('has no shape meaning "just write it out"', () => {
    expect(DIAGRAM_SHAPES).not.toContain('list');
    expect(DIAGRAM_SHAPES).not.toContain('none');
  });

  it('draws something for every shape in the vocabulary', async () => {
    for (const shape of DIAGRAM_SHAPES) {
      const limits = SHAPE_LIMITS[shape];
      const diagram = await diagramFor({
        shape,
        title: 'A title',
        nodes: Array.from({ length: limits.min }, (_, i) => ({ id: `n${i}`, label: `Node ${i}` })),
      });
      const { html } = renderDiagram(diagram, 0);
      // Either drawn geometry, or boxes arranged to mean something — which is
      // exactly the condition A8 used to test for.
      // `img` counts: an illustration's board is a photograph, which is as much
      // a drawing as a drawn one for the purpose this asserts — the board is not
      // a wall of text.
      const drawn = /<(?:svg|path|circle|rect|line|polyline|polygon|ellipse|img)\b/i.test(html);
      const structural = [...html.matchAll(/<(div|table|tr|td|th|aside|figure)\b/gi)].length;
      expect(drawn || structural >= 2, shape).toBe(true);
    }
  });
});

